[tool.poetry]
name = "finary_assistant"
version = "0.0.1"

[tool.semantic_release]
version_variable = [
    "finary_assistant/__meta__.py:__version__",
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = "pip install poetry && poetry build"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "$version"
